bootstrap_servers: "pkc-921jm.us-east-2.aws.confluent.cloud:9092"
topic: "payments.raw"

security_protocol: "SASL_SSL"
sasl_mechanism: "PLAIN"

sasl_username: "72I4WJOBIQ6RXQUG"
sasl_password: "cfltyu0QtjanAa5kCwxmWXaP4UK02I3iTKyF+xl3yteMRRHXNBWuEjclbqvJdQdQ"

linger_ms: 10
acks: "all"